In [35]:
# 0. load SMPL model
import easymocap
from easymocap.smplmodel import load_model
load_model
load_model(gender='male', use_cuda=True, model_type='smpl', skel_type='body25', device=None, model_path='data/smpl/')

SMPLlayer()

In [57]:
import easymocap.dataset
from easymocap.dataset.base import read_smpl
from easymocap.smplmodel import body_model
# 1. load parameters
#read_smpl('smpl/smpl/')
infos = read_smpl('smpl/smpl/000000.json')
# 2. compute joints
joints = body_model(return_verts=False, return_tensor=False, **info)[0]
# 3. compute vertices
vertices = body_model(return_verts=True, return_tensor=False, **info)[0]

NameError: name 'info' is not defined

In [36]:
#import pyrender # first import the pyrender
from collections import namedtuple
import numpy as np
from easymocap.mytools.reader import read_smpl
import os
import json
from easymocap.dataset.base import MVBase
from easymocap.dataset.config import CONFIG
# 0. load SMPL model
from easymocap.smplmodel import load_model
from os.path import join
from easymocap.mytools.cmd_loader import load_parser
from easymocap.config import Config, load_object

#parser = load_parser()
#parser.add_argument('--gender', type=str, default='neutral', choices=['male', 'female', 'neutral'])
#parser.add_argument('--model', type=str, default='smpl', choices=['none', 'smpl', 'smplx'])
#args = parser.parse_args()

#body_model = load_model(args.gender, model_type=args.model)
# 1. load parameters
nf=0
step=1
smpl_output_path='smpl/smpl'
def read_json(path):
    with open(path) as f:
        data = json.load(f)
    return data
def read_smpl(nf):
        outname = join(smpl_output_path, '{:06d}.json'.format(nf))
        assert os.path.exists(outname), outname
        datas = read_json(outname)
        outputs = []
        for data in datas:
            for key in ['Rh', 'Th', 'poses', 'shapes']:
                data[key] = np.array(data[key])
            outputs.append(data)
        return outputs
infos = read_smpl(nf*step)
#print(infos)
'''
[{'id': 0, 'Rh': array([[ 1.279, -1.263, -1.197]]), 'Th': array([[0.42 , 0.285, 1.168]]), 'poses': array([[ 0.   ,  0.   ,  0.   , -0.067,  0.093,  0.162, -0.147, -0.082,
        -0.096,  0.   ,  0.   , -0.   ,  0.022,  0.044, -0.073,  0.094,
        -0.049,  0.042, -0.   ,  0.   ,  0.   , -0.043,  0.136, -0.004,
        -0.004, -0.144,  0.024,  0.034,  0.   ,  0.   , -0.   ,  0.   ,
        -0.   ,  0.   ,  0.   , -0.   , -0.288,  0.39 ,  0.043,  0.   ,
         0.   ,  0.   , -0.   ,  0.   ,  0.001,  0.281,  0.353,  0.019,
        -0.03 , -0.1  , -0.368, -0.027,  0.071,  0.426, -0.018, -0.158,
         0.065, -0.01 ,  0.091,  0.013, -0.   ,  0.   ,  0.   ,  0.   ,
        -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,  0.   ]]), 'shapes': array([[ 0.188, -0.178,  0.054,  0.178,  0.027,  0.035, -0.021, -0.022,
         0.018, -0.015]])}]
'''
for info in infos:
    #config = Config.load(args.cfg)
    body_model=load_model('male','smpl')
    #body_model = load_object(config.module, config.args)
# 2. compute joints
    #params = body_model.init_params(1)
    pose=info["poses"]
    Rh=info["Rh"]
    Th=info["Th"]
    shapes=info["shapes"]
    #global_orient = pose[:, :3]
#taking the global orientation of the body (the first 3 columns of the pose matrix)
    #body_pose = pose[:, 3:]
    body_pose=pose
#taking the body pose (from the 4th columns to the end of the pose matrix)
    body_params = {
    'poses':body_pose,
    'shapes': shapes,
    'Rh':Th,
    'Th':Th
    #'transl': trans
    }
    #smpl_model.forward(**body_params)

#for info in infos:
    #get parameter 
    #print(data)
    

    joints = body_model(return_verts=False, return_tensor=False, **body_params)[0]
    print(joints)
# 3. compute vertices
#vertices = body_model(return_verts=True, return_tensor=False, **infos)[0]
'''
{'poses': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.]]), 'shapes': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), 'Rh': array([[0., 0., 0.]]), 'Th': array([[0., 0., 0.]])}
'''

[Load model smpl/male]
[[ 0.11139575  0.48919022  1.4449916 ]
 [ 0.20591721  0.36942452  1.2740303 ]
 [ 0.15142226  0.22553657  1.2818601 ]
 [ 0.15584391 -0.06200153  1.2105396 ]
 [ 0.17647465 -0.32680508  1.1853908 ]
 [ 0.2512911   0.511618    1.2584592 ]
 [ 0.45951337  0.7273189   1.2238953 ]
 [ 0.64015067  0.9254594   1.2383199 ]
 [ 0.6425178   0.19341624  1.0618515 ]
 [ 0.6012698   0.098171    1.0610065 ]
 [ 0.97919786 -0.07087687  0.90071225]
 [ 1.3090551  -0.22479942  0.69749177]
 [ 0.6793677   0.2900664   1.0648882 ]
 [ 1.0640378   0.18388706  0.88186395]
 [ 1.4130931   0.08554173  0.6720828 ]
 [ 0.07736829  0.4635222   1.4585067 ]
 [ 0.07789224  0.5093138   1.4250071 ]
 [ 0.04988685  0.36381146  1.4152138 ]
 [ 0.05391949  0.49543196  1.3264413 ]
 [ 1.5331894   0.08411427  0.813334  ]
 [ 1.5270165   0.11155879  0.7817917 ]
 [ 1.4292283   0.07240571  0.6308597 ]
 [ 1.4050813  -0.31211844  0.83468664]
 [ 1.3828192  -0.32648394  0.80404687]
 [ 1.3286453  -0.22256306  0.6552981 ]]


"\n{'poses': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,\n        0., 0., 0., 0., 0., 0., 0., 0.]]), 'shapes': array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]), 'Rh': array([[0., 0., 0.]]), 'Th': array([[0., 0., 0.]])}\n"

In [17]:
infos[0]

{'id': 0,
 'Rh': array([[ 1.279, -1.263, -1.197]]),
 'Th': array([[0.42 , 0.285, 1.168]]),
 'poses': array([[ 0.   ,  0.   ,  0.   , -0.067,  0.093,  0.162, -0.147, -0.082,
         -0.096,  0.   ,  0.   , -0.   ,  0.022,  0.044, -0.073,  0.094,
         -0.049,  0.042, -0.   ,  0.   ,  0.   , -0.043,  0.136, -0.004,
         -0.004, -0.144,  0.024,  0.034,  0.   ,  0.   , -0.   ,  0.   ,
         -0.   ,  0.   ,  0.   , -0.   , -0.288,  0.39 ,  0.043,  0.   ,
          0.   ,  0.   , -0.   ,  0.   ,  0.001,  0.281,  0.353,  0.019,
         -0.03 , -0.1  , -0.368, -0.027,  0.071,  0.426, -0.018, -0.158,
          0.065, -0.01 ,  0.091,  0.013, -0.   ,  0.   ,  0.   ,  0.   ,
         -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,  0.   ]]),
 'shapes': array([[ 0.188, -0.178,  0.054,  0.178,  0.027,  0.035, -0.021, -0.022,
          0.018, -0.015]])}

In [34]:
print(joints)

[[ 7.5555682e-02  4.4909945e-01  7.9092458e-02]
 [-7.4490556e-04  2.5310194e-01 -1.1841999e-02]
 [-1.5458582e-01  2.5440803e-01 -3.7168497e-03]
 [-4.2009538e-01  1.2351385e-01 -1.6195312e-02]
 [-6.5849251e-01  7.9760775e-03  1.5377577e-02]
 [ 1.4814927e-01  2.5519738e-01 -3.0453036e-02]
 [ 4.2556655e-01  1.3837624e-01 -8.7610818e-03]
 [ 6.7646176e-01  6.1096698e-02  4.7603920e-02]
 [-2.7872398e-03 -2.6246354e-01  1.6564628e-02]
 [-1.0653418e-01 -2.6010606e-01  1.4377767e-02]
 [-1.2381339e-01 -7.0110673e-01  6.2554024e-02]
 [-1.4481308e-01 -1.1172613e+00  4.9484272e-02]
 [ 1.0063827e-01 -2.5972328e-01  1.8576119e-02]
 [ 1.4426599e-01 -6.9610876e-01  3.8759504e-02]
 [ 1.8200384e-01 -1.1128699e+00  1.8620286e-02]
 [ 3.9121915e-02  4.7495845e-01  8.0899879e-02]
 [ 8.1864201e-02  4.7413602e-01  4.3593220e-02]
 [-6.3678339e-02  4.4495064e-01  4.7682796e-02]
 [ 6.0110971e-02  4.4396400e-01 -5.1795870e-02]
 [ 2.2507758e-01 -1.1473457e+00  1.9563192e-01]
 [ 2.4829671e-01 -1.1477677e+00  1.60320

In [41]:
np.shape(joints)
#np.shape(info["poses"])

(25, 3)

In [12]:
infos[0]

{'id': 0,
 'Rh': array([[ 1.279, -1.263, -1.197]]),
 'Th': array([[0.42 , 0.285, 1.168]]),
 'poses': array([[ 0.   ,  0.   ,  0.   , -0.067,  0.093,  0.162, -0.147, -0.082,
         -0.096,  0.   ,  0.   , -0.   ,  0.022,  0.044, -0.073,  0.094,
         -0.049,  0.042, -0.   ,  0.   ,  0.   , -0.043,  0.136, -0.004,
         -0.004, -0.144,  0.024,  0.034,  0.   ,  0.   , -0.   ,  0.   ,
         -0.   ,  0.   ,  0.   , -0.   , -0.288,  0.39 ,  0.043,  0.   ,
          0.   ,  0.   , -0.   ,  0.   ,  0.001,  0.281,  0.353,  0.019,
         -0.03 , -0.1  , -0.368, -0.027,  0.071,  0.426, -0.018, -0.158,
          0.065, -0.01 ,  0.091,  0.013, -0.   ,  0.   ,  0.   ,  0.   ,
         -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,  0.   ]]),
 'shapes': array([[ 0.188, -0.178,  0.054,  0.178,  0.027,  0.035, -0.021, -0.022,
          0.018, -0.015]])}

In [1]:
import numpy as np
aa=np.array([-0.067,  0.093,  0.162])


rot_mat = pytorch3d.transfroms.axis_angle_to_matrix(aa)

# Euler angles
euler = pytorch3d.transfroms.matrix_to_euler_angles(rot_mat, convention)

NameError: name 'pytorch3d' is not defined

In [2]:
import pytorch3d
pytorch3d.transforms

AttributeError: module 'pytorch3d' has no attribute 'transforms'

In [9]:
import pytorch3d
import torch

In [3]:
from  pytorch3d import _C


ImportError: libc10.so: cannot open shared object file: No such file or directory

In [13]:
import torch
from pytorch3d import transforms

ImportError: cannot import name 'transforms' from 'pytorch3d' (unknown location)